version: '3.9'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=abcd
      - POSTGRES_USER=ali
      - POSTGRES_DB=stockdb
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8091
    volumes:
      - .:/app/
    ports:
      - 8091:8091
    depends_on:
      - db
volumes:
  pgdata:
  
